version: '3'
services:
  BOEngine:
    # image: hub.c.163.com/lingd3/boengine:1.0
    image: ren/boengine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"  
          memory: 500M 
      restart_policy:  
        condition: on-failure  
    ports:
      - "10232:10232"
    networks:  
      - webnet

networks:  
  webnet: 
