version: '3'
services:
  EurekaServer:
    # image: hub.c.163.com/lingd3/eurekaserver:1.0
    image: ren/eurekaserver
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"  
          memory: 500M 
      restart_policy:  
        condition: on-failure 
    ports:
      - "10236:10236"
    networks:  
      - webnet

networks:  
  webnet: 
