version: '3'
services:
  RenNameService:
    # image: hub.c.163.com/lingd3/rennameservice:1.0
    image: ren/rennameservice
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"  
          memory: 300M 
      restart_policy:  
        condition: on-failure  
    ports:
      - "10234:10234"
    networks:  
      - webnet

networks:  
  webnet: 
