version: '3'
services:
  RenResourceService:
    # image: hub.c.163.com/lingd3/renresourceservice:1.0
    image: ren/renresourceservice
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"  
          memory: 300M 
      restart_policy:  
        condition: on-failure  
    ports:
      - "10233:10233"
    networks:  
      - webnet

networks:  
  webnet: 
